Metrics/LineLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.4
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Layout/IndentHash:
  EnforcedStyle: consistent
